heroku config:add LOGIN_SERVER="https://login.salesforce.com" \
    CLIENT_ID="*************************************************************************" \
    CLIENT_SECRET="*****************" \
    USERNAME="streaming@df11.pat" \
    PASSWORD="********" \
    TWILIO_SID="**********************************" \
    TWILIO_TOKEN="********************************" \
    TWILIO_NUMBER="+14087248777" \
    DEBUG="true"